#!/bin/bash

set -euo pipefail
# Workaround to replace all system includes with user includes
echo "$GCC_ARM_NONE_EABI_FILES_GCC" "${@}" -fdiagnostics-color=always >&2
"$GCC_ARM_NONE_EABI_FILES_GCC" "${@}" -fdiagnostics-color=always
